'use client'

import { CssBaseline } from '@mui/material'
import { NextAuthProvider, ColorThemeProvider, ColorModeContext } from "./providers";
import Layout from "@/components/Layout/Layout";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ColorThemeProvider>
          <NextAuthProvider>
            <CssBaseline />
              <Layout >
                {children}
              </Layout>
            </NextAuthProvider>
        </ColorThemeProvider>
      </body>
    </html>
  )
}
